articles/urls.py
from django.urls import path
from .views import article_view,article_detail, publish_article, article_update, article_delete, search_article_view


app_name = 'articles'
urlpatterns = [
    path('', article_view, name='articles'),
    path('publish/', publish_article, name='publish_article'),
    path('detail/<int:id>', article_detail, name='article_detail'),
    path('update/<int:id>', article_update, name='article_update'),
    path('delete/<int:id>', article_delete, name='article_delete'),
    path('delete/<int:id>', article_delete, name='article_delete'),
    path('search-articles/', search_article_view, name='search_articles'),
    
    
    
]

chat/urls.py
from django.urls import path
from .views import chat_view,private_chatroom_view,leave_group_view, join_group_view

app_name = 'chat'
urlpatterns = [
    path('', chat_view, name='chat'),
    path('leave-group/', leave_group_view, name='leave_group'),
    path('leave-group/', join_group_view, name='join_group'),
    path('private-chatroom/<int:user2_id>/',private_chatroom_view , name='private_chatroom')
]

feed/urls.py
from django.urls import path
from .views import feed_view

app_name = 'feed'
urlpatterns = [
    path('', feed_view, name='feed'),
]

home/urls.py
from django.urls import path
from .views import home_view, terms_of_service_view,privacy_policy_view
app_name = 'home'
urlpatterns = [
    path('', home_view,name='home'),
    path('pyacademia/terms-of-service/', terms_of_service_view,name='terms-of-service'),
    path('pyacademia/privacy-policy/', privacy_policy_view,name='privacy_policy'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('chat/', include('chat.urls')),
    path('feed/', include('feed.urls')),
    path('network/', include('network.urls')),
    path('posts/', include('posts.urls')),
    path('blogs/', include('articles.urls')),
    path('resources/', include('resources.urls')),
    path('projects/', include('projects.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')), # app 
    path("__reload__/", include("django_browser_reload.urls")), # tailwind auto reload
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


network/urls.py
from django.urls import path
from .views import network_view, search_users_view

app_name = 'network'
urlpatterns = [
    path('', network_view, name='network'),
    path('user-search/', search_users_view, name='search'),
   
]

projects/urls.py
from django.urls import path
from .views import project_view, create_project_view,project_detail_view, project_update_view, project_delete_view


app_name = 'projects'
urlpatterns = [
    path('', project_view, name='projects'),
    path('create/', create_project_view, name='create_project'),
    path('detail/<int:id>', project_detail_view, name='project_detail'),
    path('update/<int:id>', project_update_view, name='project_update'),
    path('delete/<int:id>', project_delete_view, name='project_delete'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render,redirect,HttpResponse



# Create your views here.
def custom_404_view_name(request,exception):
    return render(request, '404.html',)

def terms_of_service_view(request):
    return render(request, 'terms_of_service.html')


def privacy_policy_view(request):
    return render(request, 'privacy_policy.html')

def home_view(request):
    return render(request, 'home/home.html',)

home/templates/home/base.html

{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    
    {% tailwind_css %}
    {% block tailwind_block %}
    {% endblock %}

    {% block extra_css %}
    {% endblock %}
    {% block custom_styles %}
    {% endblock %}
    <style>
      @media (min-width: 1024px) {
          #menu-toggle {
              display: none;
          }
          #mobile-menu {
            display: none;
          }
      }
      
  </style>

</head>
<body  class="font-sans font-medium bg-gray-50">       
  <header class="bg-white shadow-md fixed top-0 w-full">
    <div class="container mx-auto flex justify-between items-center p-4 lg:px-12">
        <a class="cursor-pointer text-3xl text-indigo-600 font-bold" href="{% url 'home:home' %}">PyAcademia</a>
        <nav class="hidden lg:flex gap-4">
            <a class="{% if request.path == '/' %}text-indigo-600 {% else %} text-gray-600 {% endif %}  font-medium cursor-pointer hover:text-indigo-600" href="{% url 'home:home' %}">HOME</a> 
            <a class="{% if request.path == '/feed/' %}text-indigo-600 {% else %} text-gray-600 {% endif %} font-medium cursor-pointer hover:text-indigo-600" href="{% url 'feed:feed' %}">FEED</a> 
            <a class="{% if request.path == '/network/' %}text-indigo-600 {% else %} text-gray-600 {% endif %} font-medium cursor-pointer hover:text-indigo-600" href="{% url 'network:network' %}">NETWORK</a> 
            <a class="{% if request.path == '/blogs/' %}text-indigo-600 {% else %} text-gray-600 {% endif %} font-medium cursor-pointer hover:text-indigo-600" href="{% url 'articles:articles' %}">BLOGS</a> 
            <a class="{% if request.path == '/projects/' %}text-indigo-600 {% else %} text-gray-600 {% endif %} font-medium cursor-pointer hover:text-indigo-600" href="{% url 'projects:projects' %}">PROJECTS</a>
            <a class="{% if request.path == '/resources/' %}text-indigo-600 {% else %} text-gray-600 {% endif %} font-medium cursor-pointer hover:text-indigo-600" href="{% url 'resources:resources' %}">RESOURCES</a>
            <a class="{% if request.path == '/chat/' %}text-indigo-600 {% else %} text-gray-600 {% endif %} font-medium cursor-pointer hover:text-indigo-600" href="{% url 'chat:chat' %}">CHAT</a>
        </nav>
        <div class="lg:flex items-center space-x-4">
        </main>
            {% if request.user.is_authenticated %}
            <a class="text-gray-600 font-medium cursor-pointer hover:text-indigo-600" href="{% url 'account_logout' %}">Logout</a>
            {% else %}
            <a class="text-gray-600 font-medium cursor-pointer hover:text-indigo-600" href="{% url 'account_login' %}">Login</a>
            <a class="text-gray-600 font-medium cursor-pointer hover:text-indigo-600" href="{% url 'account_signup' %}">Signup</a>
            {% endif %}
        </div>
        <div class="lg:hidden">
            <button id="menu-toggle" class="text-gray-600 hover:text-gray-700 focus:outline-none">
                <i class="fas fa-bars text-2xl"></i>
            </button>
        </div>
    </div>
    <nav id="mobile-menu" class="hidden lg:hidden bg-white shadow-md p-4 space-y-2">
        <a class="block text-gray-600 font-medium cursor-pointer hover:text-indigo-600" href="{% url 'home:home' %}">HOME</a> 
        <a class="block text-gray-600 font-medium cursor-pointer hover:text-indigo-600" href="{% url 'feed:feed' %}">FEED</a> 
        <a class="block text-gray-600 font-medium cursor-pointer hover:text-indigo-600" href="{% url 'network:network' %}">NETWORK</a> 
        <a class="block text-gray-600 font-medium cursor-pointer hover:text-indigo-600" href="{% url 'articles:articles' %}">BLOGS</a> 
        <a class="block text-gray-600 font-medium cursor-pointer hover:text-indigo-600" href="{% url 'projects:projects' %}">PROJECTS</a>
        <a class="block text-gray-600 font-medium cursor-pointer hover:text-indigo-600" href="{% url 'resources:resources' %}">RESOURCES</a>
        <a class="block text-gray-600 font-medium cursor-pointer hover:text-indigo-600" href="{% url 'chat:chat' %}">CHAT</a>
        
    </nav>
</header>


        {% block content %}
        {% endblock %}

    <footer class="bg-indigo-600 py-6 sm:py-8">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex flex-col md:flex-row justify-between items-center text-white mb-4 md:mb-6">
                <div class="mb-2 md:mb-0">
                    <p>&copy; 2024 PyAcademia. All rights reserved.</p>
                </div>
                <div>
                    <a href="{% url 'home:privacy_policy' %}" class="text-white hover:underline mr-4">Privacy Policy</a>
                    <a href="{% url 'home:terms-of-service' %}" class="text-white hover:underline">Terms of Service</a>
                </div>
            </div>
        </div>
    </footer>

    

        <script>
          document.getElementById('menu-toggle').addEventListener('click', function() {
              var menu = document.getElementById('mobile-menu');
              menu.classList.toggle('hidden');
          });
      </script>
</body>
</html>

home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
PyAcademia | Home
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
{% endblock %}

{% block content %}
<section class="mt-16 flex items-center justify-center min-h-screen bg-cover bg-center" style="background-image: url('{% static 'images/home-bg-image.avif' %}'); padding-top: 80px;">
    <!-- Hero Content -->
    <div class="text-center text-white p-4 max-w-2xl mx-auto">
        <h1 class="text-4xl md:text-6xl font-extrabold mb-4  drop-shadow-lg">Welcome to PyAcademia</h1>
        <p class="text-lg md:text-2xl mb-6  drop-shadow-lg">Connect, Collaborate, and Learn with your peers and fellow students</p>
        <a href="{% url 'feed:feed' %}" class="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-8 rounded-lg text-lg transition duration-300 shadow-lg transform hover:scale-105">Get Started</a>
    </div>
</section>
<section class="bg-white py-16">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-16">
            <h2 class="text-3xl font-extrabold text-gray-900">About Us</h2>
            <p class="mt-4 text-lg text-gray-600">PyAcademia is a student-centric platform designed to foster collaboration and enhance learning experiences. Our mission is to connect students, enable knowledge sharing, and support skill development through an interactive and engaging platform.</p>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-12">
            <div class="bg-white p-8 rounded-lg shadow-lg text-center">
                <i class="fas fa-users fa-5x text-indigo-600 mb-4"></i>
                <h3 class="text-xl font-bold text-indigo-600 mb-2">Our Team</h3>
                <p class="text-gray-600">A dedicated team of professionals and educators passionate about making learning accessible and collaborative.</p>
            </div>
            <div class="bg-white p-8 rounded-lg shadow-lg text-center">
                <i class="fas fa-lightbulb fa-5x text-indigo-600 mb-4"></i>
                <h3 class="text-xl font-bold text-indigo-600 mb-2">Our Vision</h3>
                <p class="text-gray-600">To create a global community of learners where knowledge and resources are shared freely and equitably.</p>
            </div>
            <div class="bg-white p-8 rounded-lg shadow-lg text-center">
                <i class="fas fa-bullseye fa-5x text-indigo-600 mb-4"></i>
                <h3 class="text-xl font-bold text-indigo-600 mb-2">Our Mission</h3>
                <p class="text-gray-600">Empowering students to achieve their full potential through collaboration and continuous learning.</p>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray-100 py-16">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
            <h2 class="text-3xl font-extrabold text-gray-900">Platform Objectives</h2>
            <p class="mt-4 text-lg text-gray-600">Our platform is built with the following objectives in mind:</p>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div class="text-center">
                <div class="p-6 bg-white rounded-lg shadow-lg">
                    <h3 class="text-xl font-bold text-indigo-600 mb-2">Collaboration</h3>
                    <p class="text-gray-600">Facilitate collaborative projects and discussions among students from different backgrounds and institutions.</p>
                </div>
            </div>
            <div class="text-center">
                <div class="p-6 bg-white rounded-lg shadow-lg">
                    <h3 class="text-xl font-bold text-indigo-600 mb-2">Skill Development</h3>
                    <p class="text-gray-600">Provide resources and opportunities for students to develop and enhance their skills in various domains.</p>
                </div>
            </div>
            <div class="text-center">
                <div class="p-6 bg-white rounded-lg shadow-lg">
                    <h3 class="text-xl font-bold text-indigo-600 mb-2">Networking</h3>
                    <p class="text-gray-600">Create a network of like-minded individuals to share knowledge, experiences, and opportunities.</p>
                </div>
            </div>
        </div>
    </div>
</section>





{% endblock %}