accounts/urls.py
from django.urls import path
from .views import follow_view,unfollow_view,profile_view,about_view,create_profile_view,custom_login_redirect, CustomPasswordChangeView


app_name = 'accounts'
urlpatterns = [
    path('profile/<int:id>', profile_view, name='profile'),
    path('profile/<int:user_id>/about/', about_view, name='profile_about'),
    path('create_profile/', create_profile_view, name='create_profile'),
    path('custom-login-redirect/', custom_login_redirect, name='custom_login_redirect'),
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
    path('follow-user/<int:id>', follow_view, name='follow'),
    path('unfollow-user/<int:id>', unfollow_view, name='unfollow'),
]

chat/urls.py
from django.urls import path
from .views import chat_view,private_chatroom_view,leave_group_view, join_group_view

app_name = 'chat'
urlpatterns = [
    path('', chat_view, name='chat'),
    path('leave-group/', leave_group_view, name='leave_group'),
    path('leave-group/', join_group_view, name='join_group'),
    path('private-chatroom/<int:user2_id>/',private_chatroom_view , name='private_chatroom')
]

feed/urls.py
from django.urls import path
from .views import feed_view

app_name = 'feed'
urlpatterns = [
    path('', feed_view, name='feed'),
]

home/urls.py
from django.urls import path
from .views import home_view, terms_of_service_view,privacy_policy_view
app_name = 'home'
urlpatterns = [
    path('', home_view,name='home'),
    path('pyacademia/terms-of-service/', terms_of_service_view,name='terms-of-service'),
    path('pyacademia/privacy-policy/', privacy_policy_view,name='privacy_policy'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('chat/', include('chat.urls')),
    path('feed/', include('feed.urls')),
    path('network/', include('network.urls')),
    path('posts/', include('posts.urls')),
    path('blogs/', include('articles.urls')),
    path('resources/', include('resources.urls')),
    path('projects/', include('projects.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')), # app 
    path("__reload__/", include("django_browser_reload.urls")), # tailwind auto reload
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


network/urls.py
from django.urls import path
from .views import network_view, search_users_view

app_name = 'network'
urlpatterns = [
    path('', network_view, name='network'),
    path('user-search/', search_users_view, name='search'),
   
]

posts/urls.py
from django.urls import path
from .views import (
 
    update_post_view,
    detail_post_view,
    delete_post_view,

    related_posts_view, 
    post_like_view,
    add_comment_view,
    report_post_view,
   
    ) 

app_name = 'posts'
urlpatterns = [
 
    path('update/<int:id>/', update_post_view, name='update-post'),
    path('detail/<int:id>/', detail_post_view, name='detail-post'),
    path('delete/<int:id>//confirm', delete_post_view, name='delete-post'),
   
    path('related-posts/', related_posts_view, name='related_posts'),
    path('like-post/<int:pk>/', post_like_view, name='like_post'),
    path('add_comment/<int:post_id>/', add_comment_view, name='add_comment'),
    path('report/<int:post_id>/',report_post_view, name='report_post'),
   
    
]

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.contrib.auth import get_user_model

class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)
    
class CustomUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('username'), max_length=16,unique=True, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

class Skill(models.Model):
    skill_name = models.CharField(max_length=100,unique=True)
    def __str__(self):
        return self.skill_name
    
class University(models.Model):
    university_name = models.CharField(max_length=150,unique=True)
    def __str__(self):
        return self.university_name

class Gender(models.Model):
    gender_cateory = models.CharField(max_length=150,unique=True)
    def __str__(self):
        return self.gender_cateory
    
from datetime import date
from django.core.exceptions import ValidationError
def age_validator(value):
    today = date.today()
    age = today.year - value.year - ((today.month, today.day) < (value.month, value.day))
    if age < 13:
        raise ValidationError('Age must be 13 or greater.')
    if age > 60:
        raise ValidationError('Age must be 60 or less.')
class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    university = models.ForeignKey(University, on_delete=models.SET_NULL, null=True)
    skill = models.ForeignKey(Skill,on_delete=models.SET_NULL, null=True)
    bio = models.TextField(blank=True)
    gender = models.ForeignKey(Gender, on_delete=models.SET_NULL, null=True)
    birthday = models.DateField(validators=[age_validator],null=True)
    profile_img = models.ImageField(null=True, blank=True)
    def is_complete(self):
        required_fields = [
            self.skill,
        ]
        if not all(required_fields):
            return False
        return True
    def __str__(self):
        if self.user.is_superuser:
            return f'{self.user.username} (Superuser) profile'
        else:
            return f'({self.user.username}) profile  ({self.user.email})'

class Follow(models.Model):
    follower = models.ForeignKey(CustomUser, related_name='following', on_delete=models.CASCADE)
    following = models.ForeignKey(CustomUser, related_name='followers', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    notify = models.BooleanField(default=False)  
    def __str__(self):
        return f'{self.follower.username} is following {self.following.username}'

    



accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
# from .forms import UserCreationFormExtended, AuthenticationFormExtended
from django.contrib.auth import get_user_model
from .forms import ProfileForm
from .models import Profile,Follow,Skill
from allauth.account.views import PasswordChangeView, PasswordSetView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.models import Post
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.mail import send_mail
from django.db import IntegrityError
User = get_user_model()

from .models import Profile





@login_required(login_url='/accounts/login/')

def custom_login_redirect(request):
    user = request.user
    profile = Profile.objects.filter(user=user).first()
    if profile is not None and profile.is_complete():
        return redirect('feed:feed')
    else:
        return redirect('accounts:create_profile')
    

@login_required(login_url='/accounts/login/')
def profile_view(request, id):
    context = {}
    
    
    users_you_are_following = User.objects.filter(followers__follower=request.user).count()
    print('------------------------------------------',users_you_are_following)

    users_following_you = User.objects.filter(following__following=request.user).count()
    print('****************************8',users_following_you)
    context = {
        'users_you_are_following': users_you_are_following,
        'users_following_you': users_following_you,
    }
    
    user = get_object_or_404(User, id=id)
    other_user = get_object_or_404(User, id=id)
    is_following = Follow.objects.filter(follower=request.user, following=other_user).exists()
    context = {
        'other_user': other_user,
        'is_following': is_following
    }
     
    print('================')
    print(id)
    try:
        if user.profile.is_complete():
            user_profile = Profile.objects.filter(user=user).first()
            user_posts = Post.objects.filter(author=user)
        else:
            messages.warning(request, 'complete your profile')
            return redirect('accounts:create_profile')
    except:
        
        messages.info(request, 'please! Complete your profile')
        return redirect('accounts:create_profile')

    
    context['user_profile'] = user_profile
    context['user_posts'] = user_posts
    context['users_you_are_following'] = users_you_are_following
    context['users_following_you'] = users_following_you
    
    
    
    print('---------------')
    print(user_profile.user.username)
    print('---------------')
    
    return render(request, 'accounts/profile.html', context)


def about_view(request, user_id):
    user_profile = get_object_or_404(User, id=user_id)
    return render(request, 'accounts/profile_about.html', {'user_profile': user_profile})

@login_required(login_url='/accounts/login/')
def create_profile_view(request):
    context = {}
    
    user=request.user
    try:
        user_profile = Profile.objects.filter(user=user).first()
    except:
        messages.info(request, 'please! Complete your profile')

        return redirect('acccounts:create_profile')


    if user_profile:
        if request.method == 'POST':
            form = ProfileForm(request.POST,request.FILES, instance=user_profile)
            if form.is_valid():
                form.save()
                messages.success(request,'profile operation successfully done')
                return redirect('feed:feed')
            else:
                messages.error(request,'profile updation failed')
                return redirect('accounts:create_profile')
        else:
            form = ProfileForm(instance=user_profile)
    else:
        if request.method == 'POST':
            form = ProfileForm(request.POST, request.FILES)
            if form.is_valid():
                profile = form.save(commit=False)
                profile.user = request.user
                profile.save()
                messages.success(request,'profile operation successfully done')
                return redirect('feed:feed')
            
        else:
            form = ProfileForm()

    context['form'] = form
    return render(request, 'accounts/create_profile.html', context)
    
@login_required(login_url='/accounts/login/')
def other_user_profileview(request, id):
    context = {}
    context['id'] = id
    print('id i get is ',id)
    print('my id is ', request.user.id)
    other_user = get_object_or_404(User, id=id)
    profile = Profile.objects.filter(user=other_user).first()
    context['profile'] = profile
    
    return render(request, 'accounts/other_userprofile.html', context)



class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    success_url = reverse_lazy('feed:feed')  

    def form_valid(self, form):
        messages.success(self.request, "Password changed successfully.")
        return super().form_valid(form)

    def get_success_url(self):
        
        success_url = self.success_url
        print("Success URL:", success_url)  
        return success_url

    def get(self, *args, **kwargs):
       
        return super().get(*args, **kwargs)

    def post(self, *args, **kwargs):
        
        return super().post(*args, **kwargs)



def follow_view(request,id):
    try:
        other_user = User.objects.get(id=id)
        follow, created = Follow.objects.get_or_create(follower=request.user, following=other_user)
        if created:
            send_mail(
                subject='New Follower Alert!',
                message=f'Hi {other_user.username}, {request.user.username} has started following you.',
                from_email='noorfaras809@gmail.com',
                recipient_list=[other_user.email],
            )
            messages.info(request, f'you successfully followed {other_user.username}')
        return redirect('accounts:profile',id)
    
    except User.DoesNotExist:
        messages.error(request, f"user doesn't exist")
        return redirect('accounts:profile',id)

@login_required
def unfollow_view(request, id):
    try:
        other_user = User.objects.get(id=id)
        follow = Follow.objects.filter(follower=request.user, following=other_user)
        if follow.exists():
            follow.delete()
            
        return redirect('accounts:profile', id=id)
    except User.DoesNotExist:
        return redirect('accounts:profile', id=id)
    

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width='device-width', initial-scale=1.0">
    <title>profile</title>
    
    <link rel="stylesheet" href="{% static '/accounts/css/base.css' %}">
    
    {% block extra_css %}
    {% endblock %}
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <header class="header">
        <div class="logo">
            <a href="">
                <span class="first-word">Py</span> Academia
            </a>
            <input type="text" placeholder="Search PyAcademia">
        </div>
       <nav>
            <ul>
                <li>
                   
                    <a href="{% url 'feed:feed' %}">
                        <i class="fa-solid fa-house inactive"></i>
                    </a>
                        
                    <a href="{% url 'network:network' %}">
                        <i class="fa-solid fa-user-group inactive"></i>
                    </a>
                    <a href="">
                        <i class="fa-solid fa-comment inactive"></i>
                    </a>
                    <a href="">
                        <i class="fa-solid fa-bell inactive"></i></a>
                </li>
            </ul>
        </nav>
        <div class="profile">
            <nav>
                <ul>
                    <li>
                        {% with url=request.path %}
        <a href="{% url 'accounts:profile' %}"  class="{% if request.path == url %} aactive {% else %} ainactive {% endif %}">
        {% if user.profile.profile_img %}
            <img class="{% if request.path == url %} active {% else %} inactive {% endif %}" src="{{ user.profile.profile_img.url }}" alt="Profile Image" class="avatar">
        {% else %}
            <i class="fa-solid fa-user {% if request.path == url %} active {% else %} inactive {% endif %}"></i>
        {% endif %}
    </a>
{% endwith %}

                    </li>
                </ul>
            </nav>

        </div>
    </header>

    {% block content %}
    
    {% endblock %}


    {% block extra_javascript %}
            
    {% endblock %}
    
</body>
</html>

accounts/templates/accounts/login.html
{% load socialaccount %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
</head>
<body>
    <header class="header">
        <nav>
            <div class="logo">
                <a href="{% url 'home:home' %}">
                    <span class="first-word">Py</span> Academia
                </a>
            </div>
        </nav>
    </header>
    <div class="parent-section">
        
        <div class="register-title">
            <h1>Make the most of your learning life</h1>
        </div>
        <div class="register-card">
            <form action="" method="post">
                {% csrf_token %}
                <label>Email</label>
                    {{form.username}}
                    <label>Password</label>
                    {{form.password}}
                   
                    <p class="register-terms-para">By clicking Agree & Join, you agree to the LinkedIn <a href="">User Agreement,  Privacy Policy</a>, and <a href="">Cookie Policy.</a></p>
                    
                    <button class="logbtn" type="submit">Agree & Join</button>
            </form>
            
            <div class="horizontal-line">
                <p>or</p>
            </div>
            <div class="partylogin-auth">
                <div class="partylogin ">
                    <a href="">
                        <div class="party-title">
                            <p>Continue with Google</p>
                        </div>
                            <img src="{% static 'accounts/images/google-icon40.png' %}" alt="google-login-icon">
                    </a>
                </div>
    
                <div class="partylogin githublogin">
                    <a href="">
                        <div class="party-title">
                            <p>Continue with GitHub</p>
                        </div>
                            <img src="{% static 'accounts/images/github-icon45.png' %}" alt="github-login-icon">
                    </a>
                </div>
            </div>

            <div class="login">
                <p>New to PyAcademia?<a href="{% url 'account_signup' %}">Joinsdfsdfs Now</a></p>
            </div>


            
        </div>
        
    </div>
    
</body>
</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}
{% block extra_css %}
{% endblock %}

{% block content %}  


    <div class="bg-white shadow">
        <div class="h-56 bg-cover bg-center bg-indigo-500" >
        </div>
        <div class="flex justify-center -mt-16">
            <div class="w-24 h-24 sm:w-32 sm:h-32 bg-white rounded-full overflow-hidden border-4 border-white">
                {% if user_profile.user.profile.profile_img %}
                <img src="{{ user_profile.user.profile.profile_img.url }}" alt="Profile Picture" class="w-full h-full object-cover">
                {% else %}
                {% endif %}
            </div>
        </div>
    </div>

    <div class="text-center mt-6 sm:mt-4 px-4">
        

        <h1 class="text-2xl sm:text-3xl font-bold">{{ user_profile.user.username }}</h1>
        <p class="text-gray-600">{{ user_profile.user.profile.university }}</p>
        <p class="text-gray-700">{{ user_profile.user.profile.skill }}</p>
        <p> {{ users_you_are_following }} following</p>
        <p>{{ users_following_you }} followers</p>
        
        <div class="mt-4 flex justify-center space-x-2">
            

            {% if request.user == user_profile.user %}
            {% else %}
            {% if is_following %}
            <form class="flex justify-center items-center" action="{% url 'accounts:unfollow' user_profile.user.id %}" method="post">
                {% csrf_token %}
                <button class="block px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700" type="submit">Unfollow</button>
            
            </form>
        {% else %}
            <form action="{% url 'accounts:follow' user_profile.user.id %}" method="post">
                {% csrf_token %}
                <button class="block px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700" type="submit">Follow</button>
            </form>
        {% endif %}
        {% endif %}


            <a href="{% url 'chat:private_chatroom' user_profile.user.id %}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400">
                {% if request.user == user_profile.user %} Yourself (Me) {% else %} Message {% endif %}
            </a>
            {% if request.user.is_authenticated %}
                {% if request.user == user_profile.user %}
            <a href="{% url 'accounts:create_profile' %}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400">Update Profile</a>
            {% endif %}
            
            {% endif %}
        </div>
    </div>
    
    <div class="mt-6 bg-white shadow">
        <div class="flex justify-center space-x-2 sm:space-x-8">
            <a href="#" class="py-4 px-3 sm:px-6 block text-blue-500 border-b-2 border-blue-500 font-medium">posts</a>
            <a href="{% url 'accounts:profile_about' user_profile.user.id %}" class="py-4 px-3 sm:px-6 block text-gray-600 hover:text-blue-500">About</a>
        </div>
    </div>

    <div class="mt-6 max-w-2xl mx-auto px-4 sm:px-0">
        <div class="bg-white p-4 sm:p-6 rounded-lg shadow-md space-y-4">
            {% for post in user_posts %}
            <div class="border-b pb-4">
                <div class="flex space-x-4">
                    {% if post.author.profile.profile_img %}
                        <img src="{{ post.author.profile.profile_img.url }}" alt="Us" class="w-12 h-12 rounded-full">
                    {% else %}
                        <img src="https://via.placeholder.com/50" alt="User Avatar" class="w-12 h-12 rounded-full">
                    {% endif %}
                    <div>
                        <h3 class="text-lg font-semibold">{{post.author.username}}</h3>
                        <p class="text-gray-500 text-sm">{{post.created_at}}</p>
                    </div>
                </div>
                <p class="mt-2 text-gray-700">{{post.title}}</p>
                {% if post.description %}
                    <p class="text-sm mb-2 break-words">{{ post.description|truncatechars:300 }}
                        {% if post.description|length > 300 %} 
                            <a class="text-indigo-600" href="{% url 'posts:detail-post' post.id %}">MORE</a>
                        {% endif %}</p>
                {% endif %}
                {% if post.post_img %}
                <img src="{{ post.post_img.url }}" alt="Post Image" class="mt-2 rounded-lg w-full object-cover">
                {% endif %}
               
            </div>
            {% endfor %}
            
        </div>
    </div>
    

{% endblock %}

accounts/templates/accounts/profile_about.html
{% extends 'base.html' %}

{% load static %}
{% block extra_css %}
{% endblock %}

{% block content %}  


    <div class="bg-white shadow">
        <div class="h-56 bg-cover bg-center bg-indigo-500">
        </div>
        <div class="flex justify-center -mt-16">
            <div class="w-24 h-24 sm:w-32 sm:h-32 bg-white rounded-full overflow-hidden border-4 border-white">
                {% if user_profile.profile.profile_img %}
                <img src="{{ user_profile.profile.profile_img.url }}" alt="Profile Picture" class="w-full h-full object-cover">
                {% else %}
                {% endif %}
            </div>
        </div>
    </div>

    <div class="text-center mt-6 sm:mt-4 px-4">
        

        <h1 class="text-2xl sm:text-3xl font-bold">{{ user_profile.username }}</h1>
        <p class="text-gray-600">{{ user_profile.email }}</p>
        <p class="text-gray-700">{{ user_profile.profile.skill }}</p>
        <p>{{ users_you_are_following }} following</p>
        <p>{{ users_following_you }} followers</p>
        
        <div class="mt-4 flex justify-center space-x-2">
            

            {% if is_following %}
            <form action="{% url 'accounts:unfollow' user_profile.id %}" method="post">
                {% csrf_token %}
                <button class="block px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700" type="submit">Unfollow</button>
            </form>
        {% else %}
            <form action="{% url 'accounts:follow' user_profile.id %}" method="post">
                {% csrf_token %}
                <button class="block px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700" type="submit">Follow</button>
            </form>
        {% endif %}


            <a href="{% url 'chat:private_chatroom' user_profile.id %}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400">Message</a>
            {% if request.user.is_authenticated %}
                {% if request.user == user_profile.user %}
            <a href="{% url 'accounts:create_profile' %}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400">Update Profile</a>
            {% endif %}
            
            {% endif %}
        </div>
    </div>
    
    <div class="mt-6 bg-white shadow">
        <div class="flex justify-center space-x-2 sm:space-x-8">
            <a href="{% url 'accounts:profile' user_profile.id %}" class="py-4 px-3 sm:px-6 block  font-medium">posts</a>
            <a href="#" class="py-4 px-3 sm:px-6 block text-indigo-600 border-b-2 border-indigo-500 hover:text-indigo-700">About</a>
        </div>
    </div>

    <div class="mt-6 max-w-2xl mx-auto px-4 sm:px-0">
        <div class="border-b pb-4 bg-white p-4 sm:p-6 rounded-lg shadow-md space-y-4">
            {% if user_profile.profile %}
                <p>{{user_profile.profile.bio}}</p>
            {% else %}
            <p>bio is not set</p>
            {% endif %}
        </div>
    </div>
    

{% endblock %}

accounts/templates/accounts/signup.html
{% load socialaccount %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'accounts/css/register.css' %}">
</head>
<body>
    <header class="header">
        <nav>
            <div class="logo">
                <a href="{% url 'home:home' %}">
                    <span class="first-word">Py</span> Academia
                </a>
            </div>
        </nav>
    </header>
    <div class="parent-section">
        
        <div class="register-title">
            <h1>Make the most of your learning life</h1>
        </div>
        <div class="register-card">
            <form action="" method="post">
                {% csrf_token %}
                <label>Username</label>
                {{form.username}}
                <label>Email</label>
                {{form.email}}
                <label>Password</label>
                {{form.password1}}
                <label>Confirm Password</label>
                {{form.password2}}
                <p class="register-terms-para">By clicking Agree & Join, you agree to the LinkedIn <a href="">User Agreement,  Privacy Policy</a>, and <a href="">Cookie Policy.</a></p>
                    
                <button class="joinbtn" type="submit">Agree & Join</button>
            </form>

            <div class="horizontal-line">
                <p>or</p>
            </div>
            <div class="partylogin-auth">
                <div class="partylogin ">
                    <a href="{% provider_login_url 'google' %}">
                        <div class="party-title">
                            <p>Continue with Google</p>
                        </div>
                            <img src="{% static 'accounts/images/google-icon40.png' %}" alt="google-login-icon">
                    </a>
                </div>
    
                <div class="partylogin githublogin">
                    <a href="">
                        <div class="party-title">
                            <p>Continue with GitHub</p>
                        </div>
                            <img src="{% static 'accounts/images/github-icon45.png' %}" alt="github-login-icon">
                    </a>
                </div>
            </div>

            <div class="login">
                <p>Already on PyAcademia? <a href="{% url 'account_login' %}">Sign in</a></p>
            </div>


            
        </div>
    </div>
    
</body>
</html>